name: Deploy to S3

on:
  push:
    branches:
      - deploy  # Triggers when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Bun.js, alternative to Node.js
      - name: Set up Bun.js
        uses: oven-sh/setup-bun@v2
        

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Build the Nuxt.js app
      - name: Build Nuxt.js
        run: bun run generate

      # Deploy to S3
      - name: Deploy
        uses: reggionick/s3-deploy@v4
        with:
          folder: .output/public
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          no-cache: true
          private: true
          